version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=marketing_database
      - POSTGRES_PORT=5432
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend:/app/backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=marketing_database
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
